title: Nimagna Hazra
logo: /assets/img/Hazra_Nimagna-007.jpg
description: Analytics Professional with 3+ years of experience in strategizing data-driven decisions that empower billion-dollar businesses
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
